<template>
  <div class="about-page text-center" data-page="about">
    <img src="/static/images/koa_logo.png" alt="Koa boilerplate is very cool" class="logo img-responsive">
    <h2>Learn about
      <a href="https://github.com/koajs-templates/ejs">koajs-templates/ejs</a>
    </h2>
    <router-link to="/">Go to home</router-link>
    <h3>This template is generated by
      <a href="https://www.npmjs.com/package/koajs-cli">koajs-cli</a>
    </h3>
  </div>
</template>

<script>
  export default {
    name: "About"
  }
</script>
