<template>
  <div class="home-page text-center">
    <img src="/static/images/koa_logo.png" class="logo img-responsive" />
    <i class="logo"></i>
    <h2>Welcome koajs-templates/ejs</h2>
    <router-link to="/about">Go to about</router-link>
    <h3>This template is generated by
      <a href="https://www.npmjs.com/package/koajs-cli">koajs-cli</a>
    </h3>
  </div>
</template>

<script>
  export default {
    name: "Home"
  }
</script>
